name: Deploy Elasticsearch to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'docker-compose.es.yml'

jobs:
  deploy-es:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload docker-compose.es.yml to ES EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_ES_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_ES_SSH_KEY }}
          source: "docker-compose.es.yml"
          target: "/home/ec2-user/opale_es"
          overwrite: true

      - name: Deploy Elasticsearch on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_ES_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_ES_SSH_KEY }}
          script: |
            set -e
            cd /home/ec2-user/opale_es

            echo "🚀 Elasticsearch 컨테이너 시작"
            docker-compose -f docker-compose.es.yml up -d

            echo "🔎 컨테이너 상태:"
            docker ps -a
