version: "3.9"

services:
  opale-es:
    build:
      context: .
      dockerfile: Dockerfile.es
    container_name: opale-es
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - /home/ec2-user/es-data:/usr/share/elasticsearch/data
